# Generated by Django 5.0.4 on 2024-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('cpwd', models.CharField(max_length=50)),
            ],
        ),
    ]
