# Generated by Django 5.0.4 on 2024-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('cpwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
