# Generated by Django 5.0.4 on 2024-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_employee_reg_address_employee_reg_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_reg',
            name='pnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
