# Generated by Django 5.0.4 on 2024-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noofdays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
