# Generated by Django 5.0.4 on 2024-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0003_user_description_user_fromdate_user_submitteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
