# Generated by Django 5.0.4 on 2024-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0004_alter_user_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='econtact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
