# Generated by Django 5.0.4 on 2024-05-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0010_usercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usercount',
        ),
    ]
