# Generated by Django 5.0.4 on 2024-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0011_delete_usercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
