# Generated by Django 5.0.4 on 2024-05-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0012_alter_user_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=100)),
                ('department_head', models.CharField(max_length=100)),
                ('department_description', models.TextField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
    ]
