# Generated by Django 5.0.4 on 2024-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0013_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_title', models.CharField(max_length=20)),
                ('designation_code', models.CharField(max_length=100)),
                ('designation_head', models.CharField(max_length=100)),
                ('designation_description', models.TextField()),
            ],
            options={
                'db_table': 'Designation',
            },
        ),
    ]
